### ISSUE TITLE
Minor Bugs on Configuration Panel

### ISSUE THREAD

**Issue by TTangNingzhi** [codegrits/CodeGRITS#1] opened 2023-12-27 09:03 UTC
1. After using the two folder browsers, sometimes I need to click "OK" or "Cancel" 3-8 times to close the window.
2. If I set the sampling frequency as 60Hz, click "OK", then open the configuration panel again, the sampling frequency is
   shown as 30Hz.
   <img src="https://github.com/codegrits/CodeGRITS/assets/83901372/1783d4ef-84d1-400e-986d-85bc75d715d7" width="50%">
3. Sometimes after clicking "OK" on Configuration, there are such errors:
   ```
   java.lang.Throwable: ID 'CodeGRITS.AddLabelAction.[Fixed Bug 1.1]' is already taken by action 'null (null)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'null (null)' (class actions.AddLabelAction) cannot use the same ID null
   ```
   Then, if I add label during tracking, the ID cannot be correctly recorded.
   ```xml
   <action id="" path="/src/main/java/trackers/ScreenRecorder.java" timestamp="1703667309629"/>
   ```

**Comment by wanteatfruit** [comment] 2023-12-28 02:43
1. It seems to be a random bug caused by Intellij SDK Platform's `FileChooserDescriptor` class.
2. Python environment checking overrides selected frequency, fixed it by loading frequency at the end of initialization.
3. A `null` action sometimes persists and takes the place of a certain action id after removing a label. Should be fixed by adding another layer of guarantee while registering new label actions

**Closed by wanteatfruit** 2023-12-28 02:43 UTC
Labels: bug
